[manager]
ratio = [1, 2, 3]
sort_by = "natural"
sort_dir_first = true
show_hidden = false
show_symlink = true

[preview]
tab_size = 2
max_width = 1200
max_height = 1800

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]
